[rep_db_60]
# db_dsn должно быть без каких-либо кавычек
# db_dsn = 192.168.20.60:1521/gfssdb.gfss.kz
db_dsn = 172.31.33.29:1521/loader.gfss.kz
db_user = reports
db_password = reports
debug_level = 2

[sswh_db_60]
# db_dsn должно быть без каких-либо кавычек
# db_dsn = 192.168.20.60:1521/gfssdb.gfss.kz
db_dsn = 172.31.33.29:1521/loader.gfss.kz
db_user = sswh
db_password = sswh
debug_level = 2

[dasorp_db_60]
# db_dsn должно быть без каких-либо кавычек
db_dsn = 192.168.20.60:1521/gfssdb.gfss.kz
db_user = dasorp
db_password = dasorp
debug_level = 2

[rep_db_loader]
db_dsn = 172.31.33.29:1521/loader.gfss.kz
db_user = sswh
db_password = sswh
debug_level = 2
